In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## create arrays

In [3]:
a1 = np.arange(1,6)
print(type(a1), '\nshape: ', a1.shape, '\n', a1)

<class 'numpy.ndarray'> 
shape:  (5,) 
 [1 2 3 4 5]


In [4]:
a2 = np.arange(11,20,2)
print(type(a2), '\nshape: ', a2.shape, '\n', a2)

<class 'numpy.ndarray'> 
shape:  (5,) 
 [11 13 15 17 19]


## create matrix

In [5]:
m1 = np.arange(6).reshape((3,2))
print(type(m1), '\nshape: ', m1.shape, '\n', m1)

<class 'numpy.ndarray'> 
shape:  (3, 2) 
 [[0 1]
 [2 3]
 [4 5]]


### want numpy to auto-calculate the other dimension?

In [6]:
m2 = np.arange(6).reshape(2,-1)
print('shape: ', m2.shape, '\n', m2)

shape:  (2, 3) 
 [[0 1 2]
 [3 4 5]]


In [7]:
m3 = np.arange(6).reshape((3,2,-1))
print('shape: ', m3.shape, '\n', m3)

shape:  (3, 2, 1) 
 [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]


## matrix math + bool operations

In [8]:
a1 + a2 

array([12, 15, 18, 21, 24])

In [9]:
a1*a2

array([11, 26, 45, 68, 95])

In [10]:
m1 = np.arange(6).reshape(3,2)
print('shape: ', m1.shape, '\n', m1)

shape:  (3, 2) 
 [[0 1]
 [2 3]
 [4 5]]


In [11]:
3 in m1

True

In [12]:
7 in m1

False

In [13]:
m1[m1>2]

array([3, 4, 5])

In [14]:
m1_bool = m1 < 2
m1_bool

array([[ True,  True],
       [False, False],
       [False, False]])

In [15]:
m1[m1_bool]

array([0, 1])

## np.ones, np.zeros, np.full, np.random

In [16]:
z1 = np.zeros((2,3))
print('shape: ', z1.shape, '\n', z1)

shape:  (2, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
o1 = np.ones((4,2), dtype=int)
print('shape: ', o1.shape, '\n', o1)

shape:  (4, 2) 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [18]:
f1 = np.full((4,3),7, dtype='int')
print('shape: ', f1.shape, '\n', f1)

shape:  (4, 3) 
 [[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [19]:
r1 = np.random.randint(11,55,(3,4))
print('shape: ', r1.shape, '\n', r1)

shape:  (3, 4) 
 [[26 36 41 21]
 [24 47 23 12]
 [12 25 16 24]]


In [20]:
r2 = np.random.rand(3,4)
print('shape: ', r2.shape, '\n', r2)

shape:  (3, 4) 
 [[0.48116277 0.70547549 0.7857299  0.50754508]
 [0.38514301 0.8754495  0.28027984 0.19316887]
 [0.03879705 0.51231919 0.9106165  0.56453675]]


## concatenate array (vertically / horizontally)

In [21]:
vstack = np.concatenate((z1,f1),axis=0)
print('shape: ', vstack.shape, '\n', vstack)

shape:  (6, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [22]:
hstack = np.concatenate((o1,f1),axis=1)
print('shape: ', hstack.shape, '\n', hstack)

shape:  (4, 5) 
 [[1 1 7 7 7]
 [1 1 7 7 7]
 [1 1 7 7 7]
 [1 1 7 7 7]]


In [23]:
hstack.shape

(4, 5)

## numpy.ravel --> Return a contiguous flattened array. i.e. A 1-D array, containing the elements of the input, is returned.

### Note: "ravel" returns reference of original matrix and hence operations update the base matrix also

In [24]:
o1r = o1.ravel()

In [25]:
o1r

array([1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
o1r[2]=20

In [27]:
o1r

array([ 1,  1, 20,  1,  1,  1,  1,  1])

In [28]:
o1

array([[ 1,  1],
       [20,  1],
       [ 1,  1],
       [ 1,  1]])

## numpy.flatten --> Return a copy of the array collapsed into one dimension.

### Note: "flatten" returns copy of original matrix and hence operations do not update the base matrix

In [29]:
o2 = np.ones((4,3), dtype=int)
o2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
o2f = o2.flatten()
o2f

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
o2f[2] = 30
o2f

array([ 1,  1, 30,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [32]:
o2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Squeeze

## numpy.squeeze --> Remove axes of length one from a.

In [33]:
md1 = np.arange(9).reshape(3,3,1)
print('shape: ', md1.shape, '\n', md1)

shape:  (3, 3, 1) 
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


In [34]:
sq = md1.squeeze()
print('shape: ', sq.shape, '\n', sq)

shape:  (3, 3) 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
md1 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print('shape: ', md1.shape, '\n', md1)

shape:  (1, 3, 3) 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [36]:
sq = md1.squeeze()
print('shape: ', sq.shape, '\n', sq)

shape:  (3, 3) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
md1 = np.array([[[0], [1], [2]]])
print('shape: ', md1.shape, '\n', md1)

shape:  (1, 3, 1) 
 [[[0]
  [1]
  [2]]]


In [38]:
sq1 = md1.squeeze()
print('shape: ', sq1.shape, '\n', sq1)

shape:  (3,) 
 [0 1 2]


In [39]:
sq2 = md1.squeeze(0) # squeeze out axis 0
print('shape: ', sq2.shape, '\n', sq2)

shape:  (3, 1) 
 [[0]
 [1]
 [2]]


In [40]:
sq3 = md1.squeeze(2) # or alternatively md1.squeeze(-1) for reverse reference
print('shape: ', sq3.shape, '\n', sq3)

shape:  (1, 3) 
 [[0 1 2]]


___Note: the error now, cause we will try to change non-1 dimension___

In [41]:
sq4 = md1.squeeze(1) # try to squeeze out axis 1
print('shape: ', sq4.shape, '\n', sq4)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [42]:
m2 = np.random.randint(1,10,(4,1,3))
print('shape: ', m2.shape, '\n', m2)

shape:  (4, 1, 3) 
 [[[2 5 1]]

 [[8 5 9]]

 [[1 9 8]]

 [[8 9 5]]]


In [43]:
sq5 = m2.squeeze()
print('shape: ', sq5.shape, '\n', sq5)

shape:  (4, 3) 
 [[2 5 1]
 [8 5 9]
 [1 9 8]
 [8 9 5]]


### Summary of Squeeze
1. Squeeze ***removes all*** 1-D axes from the matrix  
2. However, if you provide an axis as input argument, then it ***removes only specified axis*** from the matrix. Unless, that axis is not 1-D axis, in which case it gives an error

Squeeze is used in deep learning libraries to adjust the current shape of input to match required input

## numpy.expand_dims
Expand the shape of an array.

Insert a new axis that will appear at the axis position in the expanded array shape.

In [44]:
sq

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
e1 = np.expand_dims(sq,axis=-1) # alternatively axis = 2
print('shape: ', e1.shape, '\n', e1)

shape:  (3, 3, 1) 
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [46]:
print('shape: ', sq1.shape, '\n', sq1)

shape:  (3,) 
 [0 1 2]


In [47]:
e2 = np.expand_dims(sq1, axis=(0,2))
print('shape: ', e2.shape, '\n', e2)

shape:  (1, 3, 1) 
 [[[0]
  [1]
  [2]]]


In [48]:
e3 = np.expand_dims(sq1, axis = -1)
print('shape: ', e3.shape, '\n', e3)

shape:  (3, 1) 
 [[0]
 [1]
 [2]]


### Summary of expand_dims

It is opposite of squeeze and used in deep learning libraries to adjust the current shape of input to match required input

## numpy.argmax
Returns the indices of the maximum values along an axis.

In [49]:
m1 = np.random.randint(11,99,(4,3))
print('shape: ', m1.shape, '\n', m1)

shape:  (4, 3) 
 [[33 56 49]
 [45 86 24]
 [17 56 83]
 [19 52 85]]


In [50]:
np.max(m1)

86

In [51]:
np.argmax(m1)

4

In [52]:
np.max(m1,axis=0)

array([45, 86, 85])

In [53]:
np.argmax(m1,axis=0)

array([1, 1, 3])

In [54]:
np.max(m1,axis=1)

array([56, 86, 83, 85])

In [55]:
np.argmax(m1,axis=1)

array([1, 1, 2, 2])